Install mono to /app before building gbrainy
This fixes the following build error:

    Making all in tools
    make[2]: Entering directory '/run/build/gbrainy/tools'
    /usr/lib/sdk/mono6/bin/mcs -target:winexe -out:GameXmlToGetString.exe  ./GameXmlToGetString.cs -r:../src/gbrainy.Core.dll -r:Mono.Posix
    export MONO_PATH=../src && /usr/lib/sdk/mono6/bin/mono GameXmlToGetString.exe .

    Unhandled Exception:
    System.TypeLoadException: Could not set up parent class, due to: Could not load type of field 'gbrainy.Core.Main.Game:default_color' (0) due to: Could not load file or assembly 'cairo-sharp, Version=1.10.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756' or one of its dependencies. assembly:/run/build/gbrainy/src/gbrainy.Core.dll type:Game member:(null)
      at GameXmlToGetString.Main (System.String[] args) [0x00061] in <2326c82eb00343b4a364a997caa15399>:0
    [ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not set up parent class, due to: Could not load type of field 'gbrainy.Core.Main.Game:default_color' (0) due to: Could not load file or assembly 'cairo-sharp, Version=1.10.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756' or one of its dependencies. assembly:/run/build/gbrainy/src/gbrainy.Core.dll type:Game member:(null)
      at GameXmlToGetString.Main (System.String[] args) [0x00061] in <2326c82eb00343b4a364a997caa15399>:0

I think the problem is that the gtk-sharp build step is adding the
.dll to (a subdirectory of) /app, but because Mono is being run from (a
subdirectory of) /usr that path is not in Mono's search path.